version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'devbills'
      MONGO_INITDB_ROOT_PASSWORD: 'pass123'
    ports:
      - "27017:27017"
    networks:
      - local

  app:
    depends_on:
      - mongo
    container_name: devbills_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app
      - /home/app/node_modules 
    ports:
      - "3333:3333"
    networks:
      - local

networks:
  local:
    name: local
